### ISSUE TITLE
build error Cannot find namespace 'L'

### ISSUE THREAD

**Issue by Xixi20160512** [KoRiGaN/Vue2Leaflet#291]
### Description

hello everyone
i use vue-cli@3.x & typescript template
but i got a build error
#### Steps to Reproduce
just exec`yarn build`

#### Expected Results

No error is throw
#### Actual Results

![image](https://user-images.githubusercontent.com/19320239/49494598-1de58300-f89b-11e8-962d-cc1dac7a2559.png)

**Comment by lordfuoco** [comment]
@HIMISOCOOL Can you help here ?

**Comment by HIMISOCOOL** [comment]
@lordfuoco Id have to install yarn and see if its reproducible that way, if @Xixi20160512 has just installed the package it should work as it is from npm cause its a dependency of this package, but it looks like you don't have @types/leaflet installed.

**Comment by dewey** [comment]
I just installed it via npm too and also had to manually install `@types/leaflet`.

**Comment by HIMISOCOOL** [comment]
@dewey thanks for letting me know, I have this in a project and haven't needed to do this so obviously I need to check it in isolation

**Comment by Xixi20160512** [comment]
@HIMISOCOOL hi, like @dewey I had manually install **@types/leaflet** too, but I got the same error.

**Comment by HIMISOCOOL** [comment]
@Xixi20160512 if you have v1.2.3 try import L from leaflet itself this works for my project, otherwise try npm install the master branch here, we have a beta version which should fix this but I have not found the time to test it.

**Comment by HIMISOCOOL** [comment]
@Xixi20160512 thanks for the heads up, I have just reproduced the issue. Its odd that my project at work doesnt encounter this issue

**Comment by JimmyBastos** [comment]
Any update on this? I'm using the very same setup of @Xixi20160512. I also installed `@types/leaflet`, but the error persists.

**Comment by HIMISOCOOL** [comment]
@JimmyBastos yep thats the quickest way to fix it. the code in master should not have the issue.

**Comment by DonNicoJs** [comment]
Closing this, since 2.0 does not export L at all anymore

**Comment by neXorianus** [comment]
i'm useing `"vue2-leaflet": "^2.1.1",` and still getting the types error (on `vue-cli-service serve`).

I had to install `@types/leaflet` and include @JimmyBastos 's `declare ...` file to get it running again.

**Comment by backmeupplz** [comment]
Same on 2.2.1 — had to install the types and use the declare thing.

**Comment by vinerich** [comment]
Still an issue in vue2-leaflet@2.4.2.
Not that experienced with types. For me adding the file didn't work, but adding the lines in types/index.d.ts solved it for me.

**Comment by MexsonFernandes** [comment]
https://github.com/vue-leaflet/Vue2Leaflet/issues/87#issuecomment-336560312

First,
`import L from 'leaflet'; `

then import rest modules.

**Comment by kryz81** [comment]
I can confirm the fix: you need to manually install types: npm i -D @types/leaflet

**Comment by seisenreich** [comment]
> [#87 (comment)](https://github.com/vue-leaflet/Vue2Leaflet/issues/87#issuecomment-336560312)
> 
> First,
> `import L from 'leaflet'; `
> 
> then import rest modules.

When I do this I get another eslint error:
L `  error  'L' is defined but never used  no-unused-vars`.

Having this code:

```
import Vue from "vue";
import L from "leaflet";
import { LMap, LTileLayer, LMarker } from "vue2-leaflet";
import "leaflet/dist/leaflet.css";

export default Vue.extend({
  components: {
    "l-map": LMap,
    "l-tile-layer": LTileLayer,
    "l-marker": LMarker,
  },
});
```

**Comment by Krzem0** [comment]
Hello,
FYI, today i had the same issue in my TypeScript project and most like @seisenreich, I've added shims-vue2-leaflet.d.ts with `declare module 'vue2-leaflet' {
    import * as  L from 'leaflet'
    export { L }
}` and then had to rebuild the project with npm.
Now it's working.

**Comment by DonNicoJs** [comment]
@Krzem0 @seisenreich should we add a FAQ section to the docs? would you be happy to add it?
