### ISSUE TITLE
index.d.ts does not include exported member L

### ISSUE THREAD

**Issue by drafu** [KoRiGaN/Vue2Leaflet#295]
While importing L from module using
`import {L} from 'vue2-leaflet';`
an error is being thrown:
`Module '"vue2-leaflet"' has no exported member 'L'.`

And we CANNOT use `import from leaflet` directly because some functions fail checks because leaflet sometimes uses `instanceof` and it is a huge app size increase.

### Versions
- Leaflet: v1.3.4
- Vue: v2.5.21
- Vue2Leaflet: v1.2.3

**Comment by HIMISOCOOL** [comment]
install @types/leaflet, I am unsure why it's not in your dependency tree maybe it needs to be in a different slot in the package.json for this project.

**Comment by lordfuoco** [comment]
@drafu @miyujach The reason why I did not address this is because my knowledge of TS is minimal and the reason why @HIMISOCOOL is instead answering is because he did create the TS support.
@HIMISOCOOL Could you provide a pr fix for this? or some instructions to proceed ? I would be happy to do a release afterwards.

In the meantime you can see how 'double leaflet' errors can be fixed here #281 (until I manage to release a 2.0 with leaflet as peerDependency )

**Comment by drafu** [comment]
Thank for temporary double leaflet fix. That was exactly one of the problems
Still looking for your fix as installing leaflet separately doubles the final app size.

**Comment by lordfuoco** [comment]
@drafu does it still double leaflet in the final build? It should not because webpack should prune everything beside the leaflet instance in the root of your `node_module`

**Comment by drafu** [comment]
@lordfuoco
It was just yesterday with latest versions of everything I could possibly get

**Comment by lordfuoco** [comment]
@drafu Sorry I meant after applying the `alias` fix does it still double the size?

**Comment by drafu** [comment]
@lordfuoco
Will check and reply the results today or tomorrow

**Comment by HIMISOCOOL** [comment]
> 
> 
> @types/leaflet is already installed because I genuinely use TypeScript for the whole app.
> It is just index.d.ts that lacks it. Manually rewriting that single file to add exported member fully fixes the problem and the app worlks flawlessly further on
> 
> It is just the problem that author should fix

Hey dude, can you show me what you changed? I use this project in a solution that's in UAT right now and don't see this issue

**Comment by HIMISOCOOL** [comment]
OH @lordfuoco is this library meant to re-export the L namespace?? I just import L from leaflet and the components from here.

**Comment by lordfuoco** [comment]
@HIMISOCOOL yes to try to help and mitigate the multiple leaflet references

**Comment by HIMISOCOOL** [comment]
@lordfuoco OH you added that just after I made the types, I have a few minor changes in a local branch at work, I'll add the export on Monday. The need to install @types/leaflet is still odd to me but for now you *could* add it to the readme 'requires `npm install @types/leaflet` if using typescript'

**Comment by drafu** [comment]
@HIMISOCOOL I just copied to match block from `src/main.js:29` to `types/index.d.ts:707`

![image](https://user-images.githubusercontent.com/8282894/50051417-d8d71180-0122-11e9-81c8-31954f54bf4e.png)

**Comment by HIMISOCOOL** [comment]
@drafu thanks man. @lordfuoco in the future if you are gonna add new exports definitely add them to both files like above and ideally we'd make some types for the new component too

**Comment by HIMISOCOOL** [comment]
Hey @drafu I made a pr #296 can you give it a check?

**Comment by lordfuoco** [comment]
@drafu @HIMISOCOOL I just published a new beta version containing #269  
https://www.npmjs.com/package/vue2-leaflet/v/1.2.3-beta.9

Can you please test it ?

**Comment by HIMISOCOOL** [comment]
@lordfuoco the issue still persists when I clone master so its probably going to be happening on the beta version.
Ill look at it now and get back to you.
