### ISSUE TITLE
Action initiated from LControl and popup state

### ISSUE THREAD

**Issue by mike-trueh** [KoRiGaN/Vue2Leaflet#406]
### Description

I found that if you try to create custom buttons, forms, etc. inside LControl component there is a problem with popup state. Popup not showing from the actions initiated from this button's - action is executed, but popup opens and immediately closes (in older versions of leaflet/vue/vue2leaflet you can see that popup is blinking - https://jsfiddle.net/mike_trueh/g1xv5s9y/20/).

In console you can see that action is initiated and coordinates are provided to function 

If this buttons are out from map controls popup opens normally.

#### Live Demo

https://jsfiddle.net/mike_trueh/g1xv5s9y/

#### Steps to Reproduce
Just click on buttons above map and inside LControl

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [ ] Edge
- [x] Safari 12
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions
- Leaflet: v1.5.1
- Vue: v2.6.10
- Vue2Leaflet: v2.1.1

**Comment by DonNicoJs** [comment]
@mike-trueh this should be because the click event is emitted two times / catched two times.
you can use this: ` @click.stop.prevent=` to fix your issue.

**Comment by mike-trueh** [comment]
@DonNicoJs Oh great! Thanks a lot! I spent about two days to solve that problem

**Comment by DonNicoJs** [comment]
I am glad that the issue is resolved

**Comment by mike-trueh** [comment]
I still don't fully understand why the event was executed twice in LControl?

**Comment by bezany** [comment]
@mike-trueh Hello! I think source of this behavior is event bubbling. Good article abuit this [here](https://javascript.info/bubbling-and-capturing). When you click custom control, event buble from control to map and call default click handler on map.
For see this it add `<l-map @click="window.console.log(arguments)"`
When you use `@click.stop` event not propagated to map.
But it is not stop propagantation other events: double click, drag, etc. For stop bubbling all events see below.
@DonNicoJs May be add some describe about events bubbling in documentation of LControl? Or add some configurations property for disable event bubbling in LControl and set to `true` by default. I found [special function stopPropagation](https://leafletjs.com/reference-1.5.0.html#domevent-stoppropagation) for this in leaflet utils. And [same problem with solution](https://stackoverflow.com/questions/37628635/stop-interactions-click-drag-from-propagating-on-control-leaflet) on stackoverflow. And in leaflet source code usages [disableClickPropagation function](https://github.com/Leaflet/Leaflet/blob/master/src/control/Control.Zoom.js#L94) in Control.Zoom.
For vue we can use code like this:
```js
mounted () {
  DomEvent.disableClickPropagation(this.$refs.control.$el)
}
```
I can make PR.

**Comment by DonNicoJs** [comment]
Hi @bezany yeah your suggestion is more than valid a PR would be awesome
